apiVersion: v1
kind: Secret
metadata:
  name: argocd-labs-private
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:alemakray/argocd-labs-private.git
  sshPrivateKey: |

  insecure: "false"
  enableLfs: "true"